// packages/svelte/src/BarcodeReader.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte'
	import { BrowserMultiFormatReader, BarcodeFormat } from '@zxing/library'
	import type { BarcodeEvent } from '.'

	export let onScan: (event: BarcodeEvent) => void

	const codeReader = new BrowserMultiFormatReader()

	let videoElement: HTMLVideoElement

	const scan = async () => {
		const [defaultVideoSource] = await codeReader.listVideoInputDevices()
		await codeReader.decodeFromVideoDevice(defaultVideoSource.deviceId, videoElement, (result) => {
			if (result) {
				const event = {
					text: result.getText(),
					format: BarcodeFormat[result.getBarcodeFormat()],
					timestamp: result.getTimestamp()
				}
				onScan(event)
			}
		})
	}

	const cleanup = () => {
		codeReader.reset()
	}

	const preventDefaultContextMenu = (event: Event) => {
		event.preventDefault()
	}

	onMount(scan)
	onDestroy(cleanup)
</script>

<video
	bind:this={videoElement}
	controls={false}
	autoPlay={true}
	muted={true}
	playsInline={true}
	disablePictureInPicture={true}
	class={$$props.class}
	style={$$props.style}
	width={$$props.width}
	height={$$props.height}
	on:contextmenu={preventDefaultContextMenu}
/>

<style>
	video {
		transform: rotateY(180deg);
	}
</style>

// packages/react/src/BarcodeReader/index.tsx
import { useEffect, useRef } from "react"
import type { CSSProperties } from "react"
import { BrowserMultiFormatReader, BarcodeFormat } from "@zxing/library"

interface BarcodeEvent {
	text: string
	format: string
	timestamp: number
}

interface BarcodeReaderProps {
	className?: string
	style?: CSSProperties
	width?: number | string
	height?: number | string
	onScan: (event: BarcodeEvent) => void
}

const BarcodeReader: React.FC<BarcodeReaderProps> = ({ onScan, ...rest }) => {
	const videoElementRef = useRef<HTMLVideoElement>(null)

	useEffect(() => {
		const codeReader = new BrowserMultiFormatReader()
		let isCancelled = false

		const scan = async () => {
			const [defaultVideoSource] =
				await codeReader.listVideoInputDevices()

			if (isCancelled || !videoElementRef) return

			await codeReader.decodeFromVideoDevice(
				defaultVideoSource.deviceId,
				videoElementRef.current,
				(result) => {
					if (result) {
						onScan({
							text: result.getText(),
							format: BarcodeFormat[result.getBarcodeFormat()],
							timestamp: result.getTimestamp()
						})
					}
				}
			)
		}

		const cleanup = () => {
			isCancelled = true
			codeReader.reset()
		}

		scan()

		return cleanup
	}, [onScan])

	return (
		<video
			ref={videoElementRef}
			controls={false}
			autoPlay={true}
			muted={true}
			playsInline={true}
			disablePictureInPicture={true}
			onContextMenu={(event) => event.preventDefault()}
			style={{ transform: "rotateY(180deg)" }}
			{...rest}
		/>
	)
}

export default BarcodeReader
